name: Current version
description: Get the current version of the formula

inputs:
  formula_name:
    description: Name of the Homebrew formula
    required: true

runs:
  using: composite
  steps:
    - name: current version
      shell: bash
      run: |
        formula_file="Formula/${{ inputs.formula_name }}.rb"

        if [[ -f $formula_file ]]; then
          CUR_VERSION=$(grep -oP "version \"\K[\d.]+(?=\")" $formula_file)
        else
          CUR_VERSION="0"
        fi

        echo "CUR_VERSION=$CUR_VERSION" >> "$GITHUB_OUTPUT"
